
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat May 12 00:45:39 CST 2018
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int resClean = 67;
  public static final int simOr = 48;
  public static final int igualigual = 54;
  public static final int resIf = 22;
  public static final int mul = 32;
  public static final int resVoid = 15;
  public static final int resOverride = 16;
  public static final int mod = 34;
  public static final int resProtected = 8;
  public static final int dosPuntos = 40;
  public static final int resDibujar = 64;
  public static final int resPrint = 63;
  public static final int resReturn = 17;
  public static final int resNew = 5;
  public static final int resElse = 23;
  public static final int coma = 38;
  public static final int igual = 36;
  public static final int comMul = 62;
  public static final int comLin = 61;
  public static final int resSwitch = 25;
  public static final int resPrivate = 7;
  public static final int resImport = 2;
  public static final int caracter = 60;
  public static final int llavec = 46;
  public static final int llavea = 45;
  public static final int menosmenos = 30;
  public static final int iden = 59;
  public static final int resContinue = 19;
  public static final int masmas = 29;
  public static final int resPublic = 6;
  public static final int menos = 31;
  public static final int menor = 51;
  public static final int EOF = 0;
  public static final int parc = 44;
  public static final int resString = 14;
  public static final int mas = 28;
  public static final int para = 43;
  public static final int error = 1;
  public static final int corc = 42;
  public static final int resChar = 11;
  public static final int resClass = 3;
  public static final int mayor = 50;
  public static final int cora = 41;
  public static final int entero = 56;
  public static final int menorigual = 53;
  public static final int pot = 35;
  public static final int resDo = 24;
  public static final int resBoolean = 10;
  public static final int punto = 39;
  public static final int resCase = 26;
  public static final int resErrores = 65;
  public static final int puntoComa = 37;
  public static final int resTabla = 66;
  public static final int mayorigual = 52;
  public static final int resBreak = 18;
  public static final int diferente = 55;
  public static final int resInt = 13;
  public static final int resDouble = 12;
  public static final int resFor = 21;
  public static final int simNot = 49;
  public static final int simAnd = 47;
  public static final int resDefault = 27;
  public static final int div = 33;
  public static final int resFinal = 9;
  public static final int resWhile = 20;
  public static final int resExtends = 4;
  public static final int decimal = 57;
  public static final int cadena = 58;
}

